### PR TITLE
Fix indentation in `for`, `doseq` bindings (including `:let`)

### LINKED ISSUE #73: Handle the :let modifier for doseq and for
When using the `:let` modifier for macros such as `for` and `doseq`, cljfmt does not format indentation correctly.

Example:

```clojure
(for [x (range 10)
      :let [y
            (+ x 1)
            z
            (+ x 2)]]
  (println x y z))

(doseq [x (range 10)
        :let [y
              (+ x 1)
              z
              (+ x 2)]]
  (println x y z))
```

Expected:

```clojure
(for [x (range 10)
      :let [y
              (+ x 1)
            z
              (+ x 2)]]
  (println x y z))
```

### LINKED ISSUE #76: Doseq and for should use let-style indentation
All the indicated lines should be indented:

```
(for [x
      [1 2 3] ; <--
      y
      [4 5 6]] ; <--
  [x y])

(doseq [x
        [1 2 3] ; <--
        y
        [4 5 6]] ; <--
  (println x y))
```

When fixing this, we should do a quick skim to see if there are other `IndentListBody`s that should be `IndentLet`s.

### PR DESCRIPTION
**Pull request by mrkam2**
This PR is fixing indentation in `for` and `doseq` bindings, as well as nested `:let` bindings.

Fixes #76. Fixes #73.

### CODE REVIEW

**Comment by mrkam2** [comment]
@cespare Here is the PR

**Comment by cespare** [comment]
Thanks! Can you update the PR title and description to reflect the changes you implemented?

If your PR fully addresses #73 and #78, [link the relevant commit to those issues](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) so that they will be closed when the PR is merged.

**Comment by mrkam2** [comment]
@cespare Do you know how to give me permissions to assign you as a reviewer?

**Comment by cespare** [comment]
@mrkam2 only people with access to this project can assign reviewers. I added you and @apesic who has previously worked on this code.

I'm very underwater on code reviews at the moment so I'd like @apesic to review and I'll give it a quick skim and merge it once he's done.

Bump on my previous comment:

> If your PR fully addresses #73 and #78, link the relevant commit to those issues so that they will be closed when the PR is merged.

File: format/format.go [hunk 1]
```diff
@@ -235,12 +235,52 @@ func (p *Printer) applySpecialIndentRules(node *parse.ListNode) {
...
+		case IndentFor:
+			p.applySpecialFor(node.Nodes)
 		case IndentDeftype:
 			p.applySpecialDeftype(node.Nodes)
 		}
 	}
 }
 
+func (p *Printer) applySpecialForLet(nodes []parse.Node) {
+	i := -1
```
Comment (apesic) [inline format/format.go:247]: Rather than managing this index manually, you could use the index provided by the `for` loop:

```go
for i, node := range nodes {
  ...
}
```

**Review by apesic — APPROVED** [review]
Just one small comment, otherwise LGTM.

File: format/format.go (hunk 1 above)
Comment (mrkam2) [reply format/format.go:247]: I can't do that because I'm skipping some nodes.

**Comment by mrkam2** [comment]
@cespare I'm going to change the testcase file from `.txt` to `.clj` and merge this PR if you don't object.

File: format/format.go [hunk 2]
```diff
@@ -235,12 +235,52 @@ func (p *Printer) applySpecialIndentRules(node *parse.ListNode) {
...
+	seenLet := false
```
Comment (cespare) [inline format/format.go:248]: `seenLet` seems like the wrong name, since the meaning is actually "was the previous node a `let`". Maybe `prevLet` or something like that?

File: format/format.go [hunk 3]
```diff
@@ -235,12 +235,52 @@ func (p *Printer) applySpecialIndentRules(node *parse.ListNode) {
...
+			if k.Val == ":let" {
+				seenLet = true
+			}
+		}
+	}
+}
+
+func (p *Printer) applySpecialFor(nodes []parse.Node) {
+	for _, node := range nodes[1:] {
+		if goclj.Newline(node) {
```
Comment (cespare) [inline format/format.go:273]: Wouldn't you want to skip any non-semantic nodes here?

```
(for ; blah
  [x
     [1 2 3]]
  ...)
```

(Seems like some of the existing special forms have this mistake as well.)

File: format/format_test.go [hunk 4]
```diff
@@ -130,6 +130,11 @@ func TestIssue41(t *testing.T) {
 	testChangeCustom(t, file, file, f)
 }
 
+func TestDoSeqLet(t *testing.T) {
+	const file = "doseq_let.txt"
+	testChange(t, file, file)
```
Comment (cespare) [inline format/format_test.go:135]: If you just want to check that a fixture file is unchanged after formatting, use `testFixture`.

I would say that there's nothing too special about this new test and I'd just add it to the list in `TestFixture`, above.

File: format/testdata/doseq_let.txt [hunk 5]
```diff
@@ -0,0 +1,4 @@
+(doseq [a
```
Comment (cespare) [inline format/testdata/doseq_let.txt:1]: Please add a test case for `for` as well. You can just put it in this same file (but give it a different filename).

**Review by cespare — APPROVED** [review]

File: format/format.go (hunk 3 above)
Comment (mrkam2) [reply format/format.go:273]: Makes sense, I replaced the rest of the places to skip non-semantic nodes instead of just newline nodes.

**Comment by cespare** [comment]
Thanks @mrkam2!
